//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoCliente.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Palabra", Namespace="http://schemas.datacontract.org/2004/07/WCFServicesAhorcado")]
    [System.SerializableAttribute()]
    public partial class Palabra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string intentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuevaPalabraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nuevaPalabraGuionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string intentos {
            get {
                return this.intentosField;
            }
            set {
                if ((object.ReferenceEquals(this.intentosField, value) != true)) {
                    this.intentosField = value;
                    this.RaisePropertyChanged("intentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuevaPalabra {
            get {
                return this.nuevaPalabraField;
            }
            set {
                if ((object.ReferenceEquals(this.nuevaPalabraField, value) != true)) {
                    this.nuevaPalabraField = value;
                    this.RaisePropertyChanged("nuevaPalabra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nuevaPalabraGuion {
            get {
                return this.nuevaPalabraGuionField;
            }
            set {
                if ((object.ReferenceEquals(this.nuevaPalabraGuionField, value) != true)) {
                    this.nuevaPalabraGuionField = value;
                    this.RaisePropertyChanged("nuevaPalabraGuion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWServiceAhorcado")]
    public interface IWServiceAhorcado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceAhorcado/GetPalabra", ReplyAction="http://tempuri.org/IWServiceAhorcado/GetPalabraResponse")]
        AhorcadoCliente.ServiceReference.Palabra GetPalabra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceAhorcado/GetPalabra", ReplyAction="http://tempuri.org/IWServiceAhorcado/GetPalabraResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference.Palabra> GetPalabraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceAhorcado/validarLetra", ReplyAction="http://tempuri.org/IWServiceAhorcado/validarLetraResponse")]
        AhorcadoCliente.ServiceReference.Palabra validarLetra(string letra, string palabra, string PalabraGuion, string intentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWServiceAhorcado/validarLetra", ReplyAction="http://tempuri.org/IWServiceAhorcado/validarLetraResponse")]
        System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference.Palabra> validarLetraAsync(string letra, string palabra, string PalabraGuion, string intentos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWServiceAhorcadoChannel : AhorcadoCliente.ServiceReference.IWServiceAhorcado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WServiceAhorcadoClient : System.ServiceModel.ClientBase<AhorcadoCliente.ServiceReference.IWServiceAhorcado>, AhorcadoCliente.ServiceReference.IWServiceAhorcado {
        
        public WServiceAhorcadoClient() {
        }
        
        public WServiceAhorcadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WServiceAhorcadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceAhorcadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceAhorcadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AhorcadoCliente.ServiceReference.Palabra GetPalabra() {
            return base.Channel.GetPalabra();
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference.Palabra> GetPalabraAsync() {
            return base.Channel.GetPalabraAsync();
        }
        
        public AhorcadoCliente.ServiceReference.Palabra validarLetra(string letra, string palabra, string PalabraGuion, string intentos) {
            return base.Channel.validarLetra(letra, palabra, PalabraGuion, intentos);
        }
        
        public System.Threading.Tasks.Task<AhorcadoCliente.ServiceReference.Palabra> validarLetraAsync(string letra, string palabra, string PalabraGuion, string intentos) {
            return base.Channel.validarLetraAsync(letra, palabra, PalabraGuion, intentos);
        }
    }
}
